openapi: 3.0.0
info:
  title: Ben-kyoh API
  version: 1.0.0

servers:
  - url: http://localhost:3000
    description: Local development server

paths:
  /api/test:
    get:
      summary: Test endpoint
      description: A simple test endpoint to verify API functionality
      operationId: testApi
      tags:
        - System
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: 'Hello, World!'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: 'Internal server error occurred'

components:
  schemas:
    Error:
      type: object
      properties:
        error:
          type: string
        message:
          type: string
        statusCode:
          type: integer
          format: int32
